version: "3.7"
services:
  #Laravel Service
  app:
    container_name: laravel-react-app
    restart: always
    tty: true
    working_dir: /var/www/app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=laravel_react_app"
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/app
    depends_on:
      - database
    links:
      - database
    networks:
      - laravel_react_network

  #DB Service
  database:
    image: mariadb:latest
    container_name: laravel-react-database
    restart: always
    working_dir: /etc/mysql
    tty: true
    environment:
      MYSQL_DATABASE: laravel_react
      MYSQL_USER: moeen
      MYSQL_ROOT_PASSWORD: basra
      MYSQL_PASSWORD: basra
    ports:
      - 3333:3306
    volumes:
      - ./.docker/db/dump.sql:/docker-entrypoint-initdb.d/laravel_react.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel_react_network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: laravel-react-server
    restart: always
    tty: true
    ports:
      - 8100:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - laravel_react_network

#Docker Networks
networks:
  laravel_react_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
